### ISSUE TITLE
Ocarina of Time: Text Shuffle stays on even if option is disabled

### ISSUE THREAD

**Issue by 03bgood** [ArchipelagoMW/Archipelago#2413] opened 2023-11-01 20:20 UTC
### What happened?

Text shuffle is still randomized, even though it's set to "off".

### What were the expected results?

Text shuffle still occurs even when the setting is disabled 

### Software

While playing

**Comment by ThePhar** [comment] 2023-11-01 20:23
Please post your spoiler log and settings .yaml file, I was just playing OoT and I did not run into this issue.

**Comment by 03bgood** [comment] 2023-11-01 20:29
> Please post your spoiler log and settings .yaml file, I was just playing OoT and I did not run into this issue.

It won't let me upload the .yami file.

**Comment by ThePhar** [comment] 2023-11-07 17:33
I need to see the YAML or spoiler so if you can't post it here, I'd recommend either uploading it else where to link here or come on our Discord and ping me @thephar, because I can not reproduce this issue. When I have it disabled, it is disabled.

**Comment by ThePhar** [comment] 2023-11-19 03:56
I'm going to close this issue for now as I don't have any other reports of this issue and I cannot reproduce. If you still have this issue, please find a way to provide that info so we can track down what caused this.

**Closed by ThePhar** 2023-11-19 03:56 UTC
Labels: is: bug/fix, meta: needs more info
